### ISSUE TITLE
Add back copy of synthborn lovebirds background for modfile.

### ISSUE THREAD

**Issue by moruzerinho6** [TeamRizu/OutFox-Serenity#7]
The modfile is looking for the the background asset in the base ssc chart folder, however we moved all graphics into a single folder and the ssc file path is looking into other chart folder.

https://github.com/TeamRizu/OutFox-Serenity/blob/291f2bdd98305ceabe379bc0b42f844d85f84ac1/OutFox%20Serenity%20Volume%201/spirai%20project%20-drazil-%20-%20synthborn%20lovebirds/lua/mods.lua#L63

**Comment by SHRMP0** [comment]
Does changing that line to `../../spirai project -drazil- - synthborn lovebirds (BMS)/synthborn-bg.png` work?
If yes, then there's no need to keep multiple copies of the same graphics

**Comment by Sudospective** [comment]
that sounds more likely to break or cause problems than having a duplicate image

**Comment by Sudospective** [comment]
wait why was this done in the first place? what if someone deletes the bms for undisclosed reasons? this will break a lot of things if this file is left on its own

**Comment by SHRMP0** [comment]
Fair enough
